### ISSUE TITLE
Would you mind explaining more about step 8?

### ISSUE THREAD

**Issue by whompyjaw** [chmaha/ArchProAudio#1]
https://github.com/chmaha/ArchProAudio?tab=readme-ov-file#8-jack2--jack-d-bus-ignore-if-using-pipewire

Hello, thank you so much for this guide. It is so so helpful. I have done pretty much all these steps except #8. I was hoping if you could elaborate on the why for this specific step? I am using pipewire (and pipewire-jack), so what is this needed for, exactly?

Trying to read more in the manual, it seems maybe `jack2-dbus` isn't needed? Also, when I try to install it, pacman prompts me 
```
looking for conflicting packages...
:: jack2-1.9.22-1 and pipewire-jack-1:1.0.7-2 are in conflict (jack). Remove pipewire-jack? [y/N] ^C
```
These notes seem to imply that `jack2-dbus` is no longer needed, but I am not 100% certain.
https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/FAQ#does-pipewire-require-dbussystemdflatpak
https://wiki.archlinux.org/title/PipeWire#Run_PipeWire_on_top_of_native_JACK

This section https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/FAQ#what-is-wrong-with-jack--pulseaudio states:
"Since 0.3.71, a jackdbus module was added so that pipewire can implement this exact same functionality,
only much more efficient." So I don't know if this means we still need `jack2-dbus` or just dbus allowed?

**Comment by chmaha** [comment]
Note that the title for that section says "ignore if using pipewire"...
